#!/bin/bash

#podman-compose stop || exit 1

podman login reg.stratal.systems --username public --password public

(
	set -e
	podman pull reg.stratal.systems/minicycle-rs
	podman tag reg.stratal.systems/minicycle-rs minicycle-rs
)

export HERE="$(realpath "$(pwd)")"

# The idea here is to save the necessary variables to .env
# so that using `podman-compose` interactively e.g. to `exec`
# into services doesn't complain about missing env vars

echo > ./.env
env | grep '^HERE=' >> ./.env
env | grep '^DOCKER_HOST=' >> ./.env
env | grep '^PODMAN_SOCKET=' >> ./.env

exec podman-compose up -d

