services:
  minicycle:
    image: reg.stratal.systems/minicycle-rs
    hostname: minicycle-rs
    container_name: minicycle-rs
    init: true
    restart: always
    gpus: all
    ports: 3030:3030
    volumes:
      - ./conf/minicycle:${HERE}/conf/minicycle:ro
      - ./data/minicycle/minicycle:${HERE}/data/minicycle/minicycle:rw
      - ./data/minicycle/gnupg:/root/.gnupg:rw
      - ./data/minicycle/ssh:/root/.ssh:rw
    working_dir: "${HERE}"
    environment:
      - "DOCKER_HOST"

