services:
  minicycle:
    image: minicycle-rs
    hostname: minicycle-rs
    container_name: minicycle-rs
    init: true
    restart: never
    ports:
      - 3030:3030
    volumes:
      - ./conf/minicycle:${HERE}/conf/minicycle:ro
      - ./data/minicycle/minicycle:${HERE}/data/minicycle/minicycle:rw
      - ./data/minicycle/gnupg:/root/.gnupg:rw
      - ./data/minicycle/ssh:/root/.ssh:rw
      - ${DOCKER_HOST}:${DOCKER_HOST}
    working_dir: "${HERE}"
    environment:
      - DOCKER_HOST

    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]

